services:
  flask-app:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    restart: always
    networks:
      - myflaskapp
    depends_on:
      - mysql-db
  
  mysql-db:
    container_name: mysql-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydb
    restart: always
    ports:
      - "3308:3306"
    networks:
      - myflaskapp
    volumes:
      - "./database/mydb_quotes.sql:/docker-entrypoint-initdb.d/install_db.sql"

networks:
  myflaskapp: 